### ISSUE TITLE
Windows 8.1, DirectX SDK

### ISSUE THREAD

**Issue by StudioAlbert** [Kj1/ofxSpout2#1]
I got this when compiling

=== example, release ===|
......\addons\ofxSpout2\libs\include\spoutDirectX.h|38|fatal error: d3d11.h: No such file or directory|
=== Build finished: 1 errors, 0 warnings (0 minutes, 0 seconds) ===|

I gues there's some directX SDK required ?

Cheers
Sebastien

**Comment by Kj1** [comment]
Yes, you need the DX sdk.  Its included in the windows SDK from windows 8:
https://msdn.microsoft.com/en-us/library/windows/desktop/ee663275(v=vs.85).aspx

some more information:
http://stackoverflow.com/questions/7910636/d3dx11-h-missing
