### ISSUE TITLE
Multiple receivers based on receiver name

### ISSUE THREAD

**Issue by samhains** [Kj1/ofxSpout2#10]
Is there a simple way to declare a receiver that will only receive textures that have been sent to a specific name?  The receiver select works, but it is not good for working with multiple receivers.....

I'm imagining something like this in the setup function:

```
receiver.setup("A"); // only receives textures sent to 'A'
receiver2.setup("B"); // only receives textures to 'B'
```

Any assistance would be greatly appreciated :)

**Comment by Kj1** [comment]
Hi,
we're not maintaining this repo anymore; but you could implement it in ofxSpout2Sender.cpp (see method updateTexture).
